---

# tasks file for roles/omero-logmonitor
- name: Include pre-tasks.yml
  ansible.builtin.import_tasks: pre-tasks.yml

- name: system packages | install dependencies
  become: true
  ansible.builtin.dnf:
    name: git
    state: present

- name: omero logmonitor | create logmonitor directories
  become: true
  ansible.builtin.file:
    path: "{{ omero_logmonitor_basedir }}"
    state: directory
    mode: 0755

- name: omero logmonitor | get logmonitor
  become: true
  ansible.builtin.git:
    dest: "{{ omero_logmonitor_logbotdir }}"
    repo: https://github.com/ome/omero-fenton.git
    version: "{{ omero_logmonitor_version }}"

- name: omero logmonitor | setup virtualenv
  become: true
  ansible.builtin.pip:
    state: present
    virtualenv: "{{ omero_logmonitor_venv }}"
    requirements: "{{ omero_logmonitor_logbotdir }}/requirements.txt"
    virtualenv_command: /usr/local/bin/ome-python3-virtualenv
  notify:
    - restart logmonitor

- name: omero logmonitor | create system user
  become: true
  ansible.builtin.user:
    name: "{{ omero_logmonitor_system_user }}"
    home: "{{ omero_logmonitor_basedir }}"
    createhome: false
    state: present
    system: true

- name: omero logmonitor | create configuration file
  become: true
  ansible.builtin.template:
    src: omero-fenton-cfg.j2
    dest: "{{ omero_logmonitor_logbotdir }}/omero-fenton.cfg"
    mode: 0644
  notify:
    - restart logmonitor

- name: omero logmonitor | create systemd file
  become: true
  ansible.builtin.template:
    dest: /etc/systemd/system/omero-logmonitor.service
    force: true
    src: systemd-system-omero-logmonitor-service.j2
    mode: 0644
  notify:
    - restart logmonitor

- name: omero | enable logmonitor systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: omero-logmonitor.service
    state: started
  when: omero_logmonitor_autostart

- name: omero | disable logmonitor systemd
  become: true
  ansible.builtin.systemd:
    enabled: false
    name: omero-logmonitor.service
    state: stopped
  when: not omero_logmonitor_autostart
