---
# Must be imported to prevent
# undeclared variable failure
- name: omero log monitor | Import ome.omero_common role
  ansible.builtin.import_role:
    name: omero_common

- name: omero log monitor  | Include ome.python3_virtualenv
  ansible.builtin.import_role:
    name: python3_virtualenv
