---
# handlers file for roles/omero-logmonitor

- name: restart logmonitor
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: omero-logmonitor
    state: restarted
  when: omero_logmonitor_autostart
